# Site settings
title: Blog X.0 - Jekyll, Dev, Systems, Life 
email: me@jadamt.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jadamt.com" # the base hostname & protocol for your site
twitter_username: jadamt
github_username:  jadamt
instagram_username: jadamt
flickr_username: jadamt

# Build settings
markdown: kramdown
